# Use root/example as user/password credentials
version: '3.1'

services:

  mern-stack-demo-mongodb:
    image: mongo
    volumes:
      - "../mongodb-data:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mernapp

# docker-compose up -d 

# connect using mongodb-compass: mongodb://root:example@localhost:27017

# docker ps -a (to find container name)
# docker exec -it <container_name> /bin/bash/ (to go into container, use powershell on Windows)
# mongosh -u root -p example (run inside the container)

